#define F_CPU 16000000UL

#include <stdint.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>

#define SET_BIT (VALUE, BIT) (VALUE |= (1 << BIT))
#define CLEAR_BIT (VALUE, BIT) (VALUE &= ~(1 << BIT))
#define TOGGLE_BIT (VALUE, BIT) (VALUE ^= (1 << BIT))
#define GET_BIT (VALUE, BIT) ((VALUE >> BIT) & 1)

// DECORAR OS DEFINES E INCLUDES ANTERIORES
int main(){
	SET_BIT(DDRB, 5); // DEFININDO A PORTA DE SAIDA
	CLEAR_BIT(PORTB, 5); //PINO 13 DO ARDUINO, GPIO 19 do ATmega 328P
	
	TCCR0A = 0x00; //SETANDO TODOS OS BITS DO REGISTRADOR TCCR0A COM 0 PARA LIMPAR
	TCCR0B = 0x05; //SETANDO 0000 0101 no registrador TCCR0B prescaler de 1024 (Tt = 64.00 us, Tovf = 16.384ms)
	TCNT0 = 0X00; // SETANDO O CONTADOR DE OVERFLOW PARA 1 (TIFR0)
	
	while(1){
		while(!GET_BIT(TIFR0, 0)); //TIFRO VAI FICAR PRESO AI ATÉ DAR OVERFLOW, NESSE CASO QUANDO O TEMPO FOR 16.384ms
		
		TOGGLE_BIT(PORTB, 5); // INVERTE O VALOR DO BIT NO PINO 13, PORTA 19
		SET_BIT(TIFR0, 0); // SETA O VALOR DO BIT 0 DO REGISTRADOR TIFRO PARA 0
	}
}